
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:856076777758:android:63f12effb8199aff0a310f",
        firebase_cli_token: "1//03j5cuJl53mCyCgYIARAAGAMSNwF-L9IrHHbDJvPM-ARGON8sd_7MlX6Oz829fZhO9KtD6uFLI7WMiw32Sl9Hauu0oV4BKg_RH08",
        android_artifact_type: "APK",
        android_artifact_path: "D:/flutter_projects/docdoc_app/build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mohamedelaraby@gmail.com",
        release_notes: "First Fastlane Firebase Distribution"
      )
  end

end
